# The public documentation URL, used for sitemap.xml
url: "http://docs.telerik.com/devtools/winforms"
site_name: WinForms
# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock]
navigation:
## List your directory names and order here, like this:
    installation,-deployment-and-distribution:
        title: Installation, Deployment and Distribution
        position: 4
    installation,-deployment-and-distribution/visual-studio-extensions:
        title: Visual Studio Extensions
        position: 6
    licensing:
        title: Licensing
        position: 5
    buttons:
        title: Buttons
        position: 6
    buttons/button:
        title: Button
        position: 0
    buttons/checkbox:
        title: CheckBox
        position: 1
    buttons/dropdownbutton:
        title: DropDownButton
        position: 2
    buttons/radiobutton:
        title: RadioButton
        position: 3
    buttons/repeatbutton:
        title: RepeatButton
        position: 4
    buttons/splitbutton:
        title: SplitButton
        position: 5
    buttons/togglebutton:
        title: ToggleButton
        position: 6
    buttons/toggleswitch:
        title: ToggleSwitch
        position: 8
    bindingnavigator:
        title: BindingNavigator
        position: 7
    calendar:
        title: Calendar
        position: 8
    carousel:
        title: Carousel
        position: 9
    chart:
        title: Chart (obsolete)
        position: 10
    chartview:
        title: ChartView
        position: 11
    checkedlistbox:
        title: ChekedListBox
        position: 12
    clock:
        title: Clock
        position: 13
    commandbar:
        title: CommandBar
        position: 14
    dataentry:
        title: DataEntry
        position: 15
    diagram:
        title: Diagram(beta)
        position: 16
    dock:
        title: Dock
        position: 17
    desktopalert:
        title: DesktopAlert
        position: 18
    dropdown-and-listcontrol:
        title: DropDown and ListControl
        position: 19
    editors:
        title: Editors
        position: 20
    forms-and-dialogs:
        title: Forms and Dialogs
        position: 21
    ganttview:
        title: GanttView
        position: 22
    gauges:
        title: Gauges
        position: 23
    gridview:
        title: GridView
        position: 24
    layoutcontrol:
        title: LayoutControl
        position: 25
    listview:
        title: ListView
        position: 26
    menus:
        title: Menus
        position: 27
    multicolumncombobox:
        title: MultiColumnComboBox
        position: 28
    pageview:
        title: PageView
        position: 29
    panels-and-labels:
        title: Panels and Labels
        position: 30
    panorama:
        title: Panorama
        position: 31
    pdfprocessing:
        title: PdfProcessing 
        position: 32
    pdfviewer:
        title: PdfViewer
        position: 33
    pivotgrid:
        title: PivotGrid 
        position: 34
    propertygrid:
        title: PropertyGrid
        position: 35
    rangeselector:
        title: RangeSelector
        position: 36
    ribbonbar:
        title: RibbonBar
        position: 37
    richtextbox:
        title: RichTextBox (obsolote)
        position: 38
    "richtexteditor":
        title: RichTextEditor
        position: 39  
    richtexteditor/getting-started:
        title: Getting Started
        position: 2   
    richtexteditor/document-elements:
        title: Document Elements
        postion: 4
    richtexteditor/document-elements/annotations:		
        title: Annotations
        position: 8
    richtexteditor/features/styles:
        title: Styles
        position: 13
    richtexteditor/features/fields-and-document-variables:
        title: Fields and Document Variables
        position: 17
    richtexteditor/features/references:
        title: References
        position: 18
    richtexteditor/features:
        title: Features
        postion: 5
    richtexteditor/import:
        title: Import/Export
        postion: 6
    richtexteditor/ui-for-applying-rich-text-formatting:
        title: UI for Applying Rich Text Formatting
        postion: 7
    richtexteditor/how-to:
        title: How-To
        postion: 14
    rotator:
        title: Rotator
        position: 40
    scheduler:
        title: Scheduler
        position: 41
    shortcuts:
        title: Shortcuts
        position: 42
    spellchecker:
        title: SpellChecker
        position: 43
    splitcontainer:
        title: SplitContainer
        position: 44
    spread-processing:
        title: SpreadProcessing
        position: 45
    track-and-status-controls:
        title: Track and Status controls
        position: 46
    treeview:
        title: TreeView
        position: 47
    wizard:
        title: Wizzard
        position: 48
    wordsprocessing:
        title: WordsProcessing
        position: 49
    ziplibrary:
        title: ZipLibrary
        position: 50
    telerik-cab-enabling-kit:
        title: Telerik Cab Enabling Kit
        position: 51
    codedui:
        title: CodedUI 
        position: 52
    telerik-presentation-framework:
        title: Telerik Presentation Framework
        position: 53
    themes:
        title: Themes
        position: 54
    tools:
        title: Tools
        position: 55
    telerik-analytics-integration:
        title: Telerik Analytics Intergration
        position: 56
    for-more-help:
        title: For More Help
        position: 57
    
## Api Reference End
## The application virtual path
baseurl: "/devtools/winforms"
## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"
# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:jt1stbj813w'
## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM